### ISSUE TITLE
Change Port From 3000

### ISSUE THREAD

**Issue by fish-not-phish** [janhq/ichigo-demo#17]
This seems like a trivial fix, but I can't figure it out myself. I'm using port 3000 for another service, is it possible to switch from port 3000 to another port and how would I accomplish that? I don't see it being used by any of the dockerfiles so it makes me feel like it's from the NPM modules? I haven't worked with NPM before so I don't know exactly how to look into it.

**Comment by nguyenhoangthuan99** [comment]
you can try this command to start frontend
```
npm start -- --port 8000
```

**Comment by fish-not-phish** [comment]
Thank you!
